In [1]:
!pip install emoji

     |████████████████████████████████| 131 kB 2.4 MB/s eta 0:00:01


In [2]:
import emoji

In [8]:
len(emoji.EMOJI_UNICODE['en'])

3521

In [9]:
emoji.EMOJI_UNICODE['en']

{':1st_place_medal:': '🥇',
 ':2nd_place_medal:': '🥈',
 ':3rd_place_medal:': '🥉',
 ':AB_button_(blood_type):': '🆎',
 ':ATM_sign:': '🏧',
 ':A_button_(blood_type):': '🅰',
 ':Afghanistan:': '🇦🇫',
 ':Albania:': '🇦🇱',
 ':Algeria:': '🇩🇿',
 ':American_Samoa:': '🇦🇸',
 ':Andorra:': '🇦🇩',
 ':Angola:': '🇦🇴',
 ':Anguilla:': '🇦🇮',
 ':Antarctica:': '🇦🇶',
 ':Antigua_&_Barbuda:': '🇦🇬',
 ':Aquarius:': '♒',
 ':Argentina:': '🇦🇷',
 ':Aries:': '♈',
 ':Armenia:': '🇦🇲',
 ':Aruba:': '🇦🇼',
 ':Ascension_Island:': '🇦🇨',
 ':Australia:': '🇦🇺',
 ':Austria:': '🇦🇹',
 ':Azerbaijan:': '🇦🇿',
 ':BACK_arrow:': '🔙',
 ':B_button_(blood_type):': '🅱',
 ':Bahamas:': '🇧🇸',
 ':Bahrain:': '🇧🇭',
 ':Bangladesh:': '🇧🇩',
 ':Barbados:': '🇧🇧',
 ':Belarus:': '🇧🇾',
 ':Belgium:': '🇧🇪',
 ':Belize:': '🇧🇿',
 ':Benin:': '🇧🇯',
 ':Bermuda:': '🇧🇲',
 ':Bhutan:': '🇧🇹',
 ':Bolivia:': '🇧🇴',
 ':Bosnia_&_Herzegovina:': '🇧🇦',
 ':Botswana:': '🇧🇼',
 ':Bouvet_Island:': '🇧🇻',
 ':Brazil:': '🇧🇷',
 ':British_Indian_Ocean_Territory:': '🇮🇴',
 ':British_Virgin_Is

In [7]:
emoji.emojize(':baseball:')

'⚾'

In [10]:
emoji_dict = {      "0": "\u2764\uFE0F",    
                    "1": ":baseball:",
                    "2": ":beaming_face_with_smiling_eyes:",
                    "3": ":downcast_face_with_sweat:",
                    "4": ":fork_and_knife:",
                   }

In [13]:
for e in emoji_dict.values():
    print(emoji.emojize(e))

❤️
⚾
😁
😓
🍴


### Read Data

In [180]:
import pandas as pd

In [181]:
train  = pd.read_csv("./EmojifiedText/train_emoji.csv", header = None)
test = pd.read_csv("./EmojifiedText/test_emoji.csv", header=None)

In [182]:
train.drop(columns=[2,3], inplace=True)

In [183]:
train.columns = ['Text', 'Label']
test.columns = ['Text', 'Label']

In [184]:
train.head()

Text  Label
0           never talk to me again      3
1  I am proud of your achievements      2
2   It is the worst day in my life      3
3                 Miss you so much      0
4                     food is life      4

In [185]:
test['Text']  = test['Text'].apply(lambda x : x[:-1])

In [186]:
test.head()

Text  Label
0             I want to eat      4
1         he did not answer      3
2            he got a raise      2
3      she got me a present      0
4  ha ha ha it was so funny      2

In [187]:
X_train = train['Text'].values
y_train = train['Label'].values

X_test = test['Text'].values
y_test = test['Label'].values

In [188]:
X_train[:5]

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life'], dtype=object)

In [189]:
y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [190]:
X_train.shape, y_train.shape

((132,), (132,))

In [191]:
X_test.shape, y_test.shape

((56,), (56,))

In [192]:
for i in range(15, 23):
    print(X_train[i], emoji.emojize( emoji_dict[str(y_train[i])]) )

Stop shouting at me 😓
Sounds like a fun plan ha ha 😁
no one likes him 😓
the game just finished ⚾
I will celebrate soon 😁
So sad you are not coming 😓
She is my dearest love ❤️
Good job 😁


## Get Embedding

In [193]:
import numpy as np

In [95]:
f = open("glove.6B.50d.txt", encoding='utf8')

In [96]:
embedding_matrix = {}

In [97]:
for line in f:
    
    values = line.split()
    word = values[0]
    emb = np.array(values[1:], dtype='float')
    
    embedding_matrix[word] = emb

In [107]:
embedding_matrix['america'].shape

(50,)

In [197]:
def get_embedding_matrix_for_data(data):
    maxLen = 10
    embedding_data = np.zeros( (len(data), maxLen, 50) )
    
    for ix in range(data.shape[0]):
        words_in_sen = data[ix].split()
        
        for ij in range(len(words_in_sen)):
            if embedding_matrix.get(words_in_sen[ij].lower()) is not None:
                embedding_data[ix][ij] =  embedding_matrix[words_in_sen[ij].lower()]
        
    return embedding_data

In [198]:
X_train = get_embedding_matrix_for_data(X_train)

In [199]:
X_test = get_embedding_matrix_for_data(X_test)

In [200]:
X_train.shape

(132, 10, 50)

In [201]:
X_test.shape

(56, 10, 50)

In [208]:
from tensorflow.keras.utils import to_categorical

In [209]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [211]:
y_train.shape

(132, 5)

In [212]:
y_test.shape

(56, 5)

### RNN/LSTM Model

In [213]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, SimpleRNN, Dense, Dropout

In [215]:
model = Sequential()
model.add( LSTM(units=64, input_shape=(10,50), return_sequences = True ) )
model.add( Dropout(0.3) )
model.add( LSTM(units=32) )
model.add(Dropout(0.2))
model.add(Dense(units=10, activation = 'relu'))
model.add(Dense(units=5, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10, 64)            29440     
_________________________________________________________________
dropout (Dropout)            (None, 10, 64)            0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                12416     
_________________________________________________________________
dropout_1 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 10)                330       
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 55        
Total params: 42,241
Trainable params: 42,241
Non-trainable params: 0
____________________________________________________

In [216]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [217]:
his = model.fit(X_train, y_train, validation_split=0.1, batch_size=32, epochs= 50 )

Epoch 1/50
4/4 [==============================] - 7s 505ms/step - loss: 1.6103 - accuracy: 0.2431 - val_loss: 1.6287 - val_accuracy: 0.0714
Epoch 2/50
4/4 [==============================] - 0s 52ms/step - loss: 1.5853 - accuracy: 0.3051 - val_loss: 1.6437 - val_accuracy: 0.0714
Epoch 3/50
4/4 [==============================] - 0s 58ms/step - loss: 1.5506 - accuracy: 0.3582 - val_loss: 1.6484 - val_accuracy: 0.0714
Epoch 4/50
4/4 [==============================] - 0s 69ms/step - loss: 1.5304 - accuracy: 0.4203 - val_loss: 1.6534 - val_accuracy: 0.1429
Epoch 5/50
4/4 [==============================] - 0s 52ms/step - loss: 1.5143 - accuracy: 0.3267 - val_loss: 1.6611 - val_accuracy: 0.2857
Epoch 6/50
4/4 [==============================] - 0s 60ms/step - loss: 1.5018 - accuracy: 0.4122 - val_loss: 1.6647 - val_accuracy: 0.2857
Epoch 7/50
4/4 [==============================] - 0s 117ms/step - loss: 1.4959 - accuracy: 0.4411 - val_loss: 1.6662 - val_accuracy: 0.2143
Epoch 8/50
4/4 [=========

In [218]:
model.evaluate(X_train, y_train)

5/5 [==============================] - 0s 11ms/step - loss: 0.2587 - accuracy: 0.8636


[0.2586902678012848, 0.8636363744735718]

In [219]:
model.evaluate(X_test , y_test)

2/2 [==============================] - 0s 28ms/step - loss: 1.4983 - accuracy: 0.5714


[1.4983221292495728, 0.5714285969734192]

### Predictions

In [221]:
y_pred = model.predict_classes(X_test)

/Users/mohit/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [222]:
y_pred

array([4, 3, 3, 2, 2, 2, 3, 2, 4, 2, 3, 2, 0, 3, 3, 3, 2, 2, 3, 2, 0, 0,
       4, 0, 3, 3, 2, 0, 3, 2, 0, 3, 3, 2, 0, 3, 2, 4, 1, 2, 0, 0, 0, 1,
       2, 2, 2, 2, 3, 3, 3, 0, 3, 2, 2, 3])

In [225]:
np.argmax(y_test, axis=1)

array([4, 3, 2, 0, 2, 0, 0, 0, 4, 2, 1, 3, 3, 2, 1, 3, 3, 2, 3, 4, 0, 2,
       4, 3, 3, 3, 3, 0, 2, 0, 0, 1, 3, 2, 0, 1, 2, 4, 4, 2, 2, 2, 0, 1,
       2, 0, 2, 2, 2, 3, 3, 0, 3, 2, 2, 3])

In [233]:
for t in range(len(test)):
    print(test['Text'].iloc[t])
    print("Prediction : ",  emoji.emojize(emoji_dict[str(y_pred[t])]) )
    print("Actual : ", emoji.emojize(emoji_dict[str( test['Label'].iloc[t] )]) )
    print()

I want to eat
Prediction :  🍴
Actual :  🍴

he did not answer
Prediction :  😓
Actual :  😓

he got a raise
Prediction :  😓
Actual :  😁

she got me a present
Prediction :  😁
Actual :  ❤️

ha ha ha it was so funny
Prediction :  😁
Actual :  😁

he is a good friend
Prediction :  😁
Actual :  ❤️

I am upset
Prediction :  😓
Actual :  ❤️

We had such a lovely dinner tonight
Prediction :  😁
Actual :  ❤️

where is the food
Prediction :  🍴
Actual :  🍴

Stop making this joke ha ha ha
Prediction :  😁
Actual :  😁

where is the ball
Prediction :  😓
Actual :  ⚾

work is hard
Prediction :  😁
Actual :  😓

This girl is messing with me
Prediction :  ❤️
Actual :  😓

are you serious ha ha
Prediction :  😓
Actual :  😁

Let us go play baseball
Prediction :  😓
Actual :  ⚾

This stupid grader is not working 
Prediction :  😓
Actual :  😓

work is horrible
Prediction :  😁
Actual :  😓

Congratulation for having a baby
Prediction :  😁
Actual :  😁

stop messing around
Prediction :  😓
Actual :  😓

any suggestions for dinn

### Prediction for Custom Text

In [294]:
inp  = "where is the food"

In [295]:
inp

'where is the food'

In [296]:
embedding_x_query = []

In [297]:
for w in inp.lower().split():
    print(w)
    e = embedding_matrix[w]
    embedding_x_query.append(e)

where
is
the
food


In [298]:
embedding_x_query = np.array(embedding_x_query)

In [299]:
embedding_x_query.shape

(4, 50)

In [300]:
if embedding_x_query.shape[0] < 10:
    embedding_x_query = np.vstack( (embedding_x_query, np.zeros((10 - len(embedding_x_query) , 50))  ) )

In [301]:
embedding_x_query.shape

(10, 50)

In [302]:
embedding_x_query = embedding_x_query.reshape(1, 10, 50)

In [303]:
embedding_x_query.shape

(1, 10, 50)

In [304]:
pred = model.predict_classes(embedding_x_query)

In [305]:
emoji.emojize( emoji_dict[ str(pred[0])] )

'🍴'